### PR TITLE
Drop unused functions / variables

### PR DESCRIPTION
**Pull request by avindra**
Noticed these weren't being used.

P.S., would you consider merging changes to drop IE8 support?

### CODE REVIEW

**Comment by erkie** [comment]
@avindra do these changes drop IE8 support or what do you mean?

**Comment by avindra** [comment]
@erkie these changes have nothing to do with ie8, its just dead code that I wanted to remove.

The P.S. was meant as a question to you--- if I made another PR which dropped IE8 support, would you be interested in merging it?

**Comment by erkie** [comment]
I'm not actively working on this project at all as the latest version is on http://www.kickassapp.com, so I don't really see a reason for deprecating IE8 if it is working. What would be the benefit?

**Comment by avindra** [comment]
One of my coworkers pulled this code into our project as an easter egg and I just had an urge to clean up the code :haircut: 

If you're not interested thats fine, let me know and close the PR

**Comment by erkie** [comment]
I don't think we should remove browser support for the sake of removing support. But thanks for this PR 😄

**Comment by avindra** [comment]
Thanks. My intention isn't really just to remove support for the sake of it. IE8 is officially deprecated by Microsoft, so `attachEvent` hacks are a thing of a bygone era. `addEventListener` works natively in every single browser today.

My coworker actually checked in the code to our local git repo, and by removing the IE8 specific hacks, it went from 1126 lines to 925 lines. Can probably still use further cleanup too.

**Pull request merged**
